name: Deploy Astro Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Set environment variables here or reference GitHub Secrets
      API_URL: ${{ secrets.PUBLIC_HOME_URL }}   # From GitHub Secrets
      NODE_ENV: "production"                    # Example of a non-sensitive variable

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6'  # Ensure this is the required version for Astro

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Astro project
      - name: Build Astro project
        run: npm run build

  # Deployment job to GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step 1: Checkout repository again for deployment
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
