name: Deploy Astro Project

on:
  push:
    branches:
      - master

permissions:
  id-token: write  # Required for ID token access
  contents: write   # Required for content write access

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.PUBLIC_HOME_URL }}   # GitHub Secrets
      NODE_ENV: "production"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6'  # Adjust to your project's requirements

      - name: Install dependencies
        run: npm install

      - name: Build the Astro project
        run: npm run build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Specify your output directory here
