name: Deploy Astro Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Set environment variables here or reference GitHub Secrets
      API_URL: ${{ secrets.PUBLIC_HOME_URL }}   # From GitHub Secrets
      NODE_ENV: "production"   # Example of a non-sensitive variable

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build Astro project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
